### ISSUE TITLE
Please provide reproducible builds

### ISSUE THREAD

**Issue by Giszmo** [ACINQ/phoenix-kmm#187]
The last comment on https://github.com/ACINQ/phoenix/issues/112 suggests that that issue might or might not get updated ever so I suggest moving it over to this new repo here. Feel free to close the other one. I will be tracking this one, too.

Issue was:

I tried to reproduce the latest version 1.4.0 of Phoenix and got a significant diff as also documented [here](https://walletscrutiny.com/android/fr.acinq.phoenix.mainnet/).

**Comment by dpad85** [comment]
Hello, and thanks for creating this issue. The current phoenix Android app will eventually migrate to this repository, and will use [lightning-kmp](https://github.com/ACINQ/lightning-kmp) instead of a modified eclair-core. We have not yet started to work on reproducibility with Kotlin-native on the lightning-kmp repo, nor on the phoenix-mmm repo, so it will take some time.

**Comment by dpad85** [comment]
This repository is obsolete and is replaced by https://github.com/ACINQ/phoenix.
